HungLaravel/routes/web.php
<?php

use App\Http\Controllers\AdminController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('user', UserController::class);
// Route::resource('test', UserController::class);
// route::prefix('admin')->group(function () {
//     // Route::resource('user', UserController::class);
//     // Route::resource('department', DepartmentController::class);
//     // Route::resource('position', PositionController::class);
//     // Route::resource('role', RoleController::class);
//     // Route::resource('changePass', ChangePassController::class);
// });
 

route::get('admin', [AdminController::class, 'index'])->name('admin');
// route::get('admin/create', [AdminController::class, 'create'])->name('create');

HungLaravel/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

HungLaravel/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\URL;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $items = [];
    public function __construct()
    {
        $this->items =
            [
                [
                    'id' => 0,
                    'name' => 'THinh Hung',
                    'user' => 'Hungt'
                ],
                [
                    'id' => 1,
                    'name' => 'Tuan',
                    'user' => 'TuanLD'
                ],
                [
                    'id' => 2,
                    'name' => 'Dung',
                    'user' => 'DungLX'
                ],
                [
                    'id' => 3,
                    'name' => 'Tuan Anh',
                    'user' => 'anhT'
                ],
            ];
    }
    public function index()
    {

        return view('user.index', [
            'title' => 'Danh Sánh',
            'data' => $this->items,
            'topTitle' => 'Danh sách User'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
 
        return view('user.create', [
            'title' => 'Create User',
            'topTitle' => "Tạo Nhân viên",
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $user = $this->items[$id]; 
        return view('user.create', [
            'title' => 'Edit User',
            'topTitle' => "Sửa Nhân viên",
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {  
        return redirect(route('user.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }


}

HungLaravel/resources/views/user/create.blade.php
@extends('layouts.main')
@section('main')
    <div>
        <a href="{{ route('user.index') }}" class="btn btn-success">Danh sách Nhân viên</a>
        @if (isset($user))
            <form action="{{route('user.update', $user['id'])}}" method="post">
                @csrf
                @method('put')
                @include('layouts.lable', ['title' => 'Name', 'name' => 'name', 'value' => $user['name']])
                @include('layouts.lable', ['title' => 'User', 'name' => 'user', 'value' => $user['user']])
                @include('layouts.button', ['nameButton' => 'Sửa nhân viên', 'name' => 'userEdit'])
            </form>
        @else
            <form action="" method="post">
                @csrf
                @method('put')
                @include('layouts.lable', ['title' => 'Name', 'name' => 'name'])
                @include('layouts.lable', ['title' => 'User', 'name' => 'user'])
                @include('layouts.button', ['nameButton' => 'Tạo nhân viên', 'name' => 'userAdd'])
            </form>
        @endif

    </div>
@endsection

HungLaravel/resources/views/user/index.blade.php
@extends('layouts.main')
@section('main')
    <div>
        <a href="{{route('user.create')}} " class="btn btn-primary">Tạo User</a>
        <table class="table table-light">
            <thead class="thead-light"> 
                <tr>
                    <th>STT</th>
                    <th>TÊN</th>
                    <th>USER</th>
                    <th>ACTION</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $key => $user)
                <tr>
                    <td>{{ $key +1}}</td>
                    <td>{{ $user['name'] }}</td>
                    <td>{{ $user['user'] }}</td>
                    <td>
                    <a href="{{ route('user.edit', $user['id']) }}" class="btn btn-warning">Edit</a>
                    <a href="#" class="btn btn-danger">DELETE</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection